version: 2

# Set the version of Python and OS
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    install:
    - python -m pip install --upgrade --no-cache-dir pip
    - python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir --group docs .

sphinx:
  fail_on_warning: true
  configuration: doc/conf.py
