version: 2

python:
  # make sure joblib is installed in the virtualenv (it is imported in
  # conf.py)
  install:
    - requirements: .readthedocs-requirements.txt
    - method: pip
      path: .

sphinx:
  fail_on_warning: true

