version: 2

# Set the version of Python and OS
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  # make sure joblib is installed in the virtualenv (it is imported in
  # conf.py)
  install:
    - requirements: .readthedocs-requirements.txt
    - method: pip
      path: .

sphinx:
  fail_on_warning: true

