version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          command: ./continuous_integration/circle/build_doc.sh
          no_output_timeout: 60m
          environment:
            MINICONDA_PATH: ~/miniconda
            CONDA_ENV_NAME: testenv
      - run: 
          command: |
            cat log.txt && \
            if grep -q "Traceback (most recent call last):" log.txt; \
            then false; \
            else true; \
            fi
      - run:
          command: |
            mkdir -p /tmp/data
            cp -R doc/_build/html /tmp/data/html
            cp log.txt /tmp/data/log.txt
      - store_artifacts:
          path: /tmp/data
