version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          command: ./continuous_integration/circle/build_doc.sh
          environment:
            MINICONDA_PATH: ~/miniconda
            CONDA_ENV_NAME: testenv
      - store_artifacts:
          path: doc/_build/html
          destination: doc
